name: deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "dependabot.yaml"
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: Genez-io/genezio-github-action@main
        with:
          genezio-version: latest
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Deploy backend
        working-directory: ./server
        run: genezio deploy
        env:
          CI: false
